# Generated by Django 5.1.3 on 2024-11-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='remaining_late_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
