

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: trackeradmin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: trackerdb
    ports:
      - "5432:5432"
    networks:
      - tracker-network

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - tracker-network

  django-web:
    build:
      context: .
    container_name: django-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis-cache
    networks:
      - tracker-network

networks:
  tracker-network:
    driver: bridge
