# Generated by Django 5.1.3 on 2024-11-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
